name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
        env:
          VITE_REMOTE_DJANGO_HOST: ${{ secrets.VITE_REMOTE_DJANGO_HOST }}
          VITE_REMOTE_VUE_HOST: ${{ secrets.VITE_REMOTE_VUE_HOST }}
          VITE_FB_KEY: ${{ secrets.VITE_FB_KEY }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VUE3_FORMS_FIREBASE }}
          channelId: live
          projectId: vue3-forms-firebase
